# Name of workflow
name: Python Test

#Trigger entry for both push and pull requests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
#Specified job(s)
jobs:
  #Test jobs to be executed
  test:
    #Operating system or environment for exectution
    runs-on: ubuntu-latest

    # Set prefered Python versions
    strategy:
      matrix:
        python-version: [3.9, 3.10.x, 3.11]

    #Steps to define the execution of workflow
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
           make install

      - name: Format Code
        run: |
           make format

      - name: Lint Code
        run: |
           make lint
      
      - name: Testing Code
        run: |
           make test

      - name: Run App
        run: |
           make run
